run:
  go: "1.20"
  concurrency: 16
  timeout: 5m
  issues-exit-code: 1
  tests: true
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  goimports:
    local-prefixes: github.com/shoman4eg/go-moy-nalog

  depguard:
    rules:
      main:
        deny:
          - pkg: errors
            desc: use "github.com/pkg/errors" instead

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/shoman4eg/go-moy-nalog)

  revive:
    rules:
      - name: blank-imports
        disabled: true

linters:
  enable:
    - dogsled
    - dupl
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - errcheck
    - goconst
    - revive
    - ineffassign
    - misspell
    - unconvert
    - govet
    - typecheck
    - depguard
    - exportloopref
    - gofmt
    - goimports
    - gosimple
    - staticcheck
  disable:
    - unused
