name: Static analysis

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

permissions:
  contents: read

env:
  GOLANGCI_LINT_VERSION: v2.12.2

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: stable

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --config=./.golangci.yml ./...

  go-consistent:
    name: go-consistent
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: stable

      - name: go-consistent
        run: go tool go-consistent -pedantic ./...

  format:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: stable

      - name: Check formatting
        run: make check-format
